sudo: required
services:
- docker

before_install:
- docker build -t dinhhuyams/expensify -f Dockerfile.dev .

script:
- docker run dinhhuyams/expensify npm run test

notifications:
  slack: kentsclub:BhLd5K8FoIAM7v4K0BrcKZUW
  email: false
