[build]
publish = "dist"
command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.deploy-preview.environment]
  API_ENDPOINT = "https://awesome-expensify-qa.herokuapp.com/"
